# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Isaac J. Michaud
description: Statistics
url: http://isaacmichaud.github.io

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

navigation:
  - text: Home
    url: /
  - text: Research
    url: /research
  - text: Docs
    url: /docs

links:
  - text: Laber Labs
    url:  "http://www.laber-labs.com"
  - text: NC State Statistics
    url:  "http://www.stat.ncsu.edu"

social:
  - service: github
    username: isaacmichaud
    link: https://github.com/isaacmichaud
  - service: twitter
    username: isaacmichaud
    link: https://twitter.com/isaacmichaud
