project:
  type: website
  output-dir: docs

website:
  title: "Isaac Michaud"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/isaacmichaud
format:
  html:
    theme: litera
    css: styles.css

editor: visual

